language: python
python:
  # 2.6 should work, but is not tested to prevent having to install
  # NumPy and SciPy from source.
  - "2.7"
  - "3.2"

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update
  - sudo apt-get install cython cython3 python-scipy python3-scipy
  - pip install scikit-learn
  - pip install .

script:
  - cd /tmp
  - nosetests --exe seqlearn
